---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: open-cats-frontend-php-service-account
  namespace: talento
  labels:
    account: open-cats-frontend-php-service-account
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-cats-frontend-php-deployment
  namespace: talento
  labels:
    app: open-cats-frontend-php
    version: v1
spec:
  selector:
    matchLabels:
      app: open-cats-frontend-php
      version: v1
  replicas: 1
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: open-cats-frontend-php
        version: v1
    spec:
      serviceAccountName: open-cats-frontend-php-service-account
      containers:
        - name: open-cats-frontend-php
          image: bancopichinchaec.azurecr.io/bp/talento/open-cats-frontend-php:#{Build.BuildId}#
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: open-cats-secret
          readinessProbe:
            httpGet:
              path: /server-status
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /server-status
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
            timeoutSeconds: 2
            failureThreshold: 3
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 200m
              memory: 256Mi
          securityContext:
            runAsUser: 33
            runAsGroup: 33
            runAsNonRoot: true
          # readOnlyRootFilesystem: true
          # fsGroup: 2000
          #      securityContext:
          #        sysctls:
          #          - name: net.ipv4.ip_unprivileged_port_start
          #            value: "0"
          volumeMounts:
            - name: attachments
              mountPath: /var/www/html/opencats/attachments
            - name: upload
              mountPath: /var/www/html/opencats/upload
      volumes:
        - name: attachments
          azureFile:
            secretName: open-cats-secret
            shareName: '#{FILE_STORAGE_ATTACHMENTS}#'
            readOnly: false
        - name: upload
          azureFile:
            secretName: open-cats-secret
            shareName: '#{FILE_STORAGE_UPLOAD}#'
            readOnly: false
---
kind: Service
apiVersion: v1
metadata:
  name: open-cats-frontend-php-service
  namespace: talento
  labels:
    app: open-cats-frontend-php
    version: v1
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: open-cats-frontend-php

# For autoscaling --- begin
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: open-cats-frontend-php-scaler
  namespace: talento
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: open-cats-frontend-php-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
# For autoscaling --- end
